Input:
    server: SQL2012PROD05
    database: Hydrotel
    mtype: flow
    site: '66401'
    quantile: 0.3
    ref_point: 2355
    new_mtype: 'Flow Detided v2'
Output:
    server: SQL2012dev01
    new_point: 7229
    quality_code: 2
    log_server: sql2014dev01
    log_database: Apps_Trace_Log
    log_table: Waimak_Log
