Input:
    hydrotel_server: SQL03PROD
    mtype: flow
    site: '66401'
    quantile: 0.3
    ref_point: 2355
    detided_mtype: 'Flow Detided v2'
    unmod_mtype: 'Flow Unmodified'
    other_mtype: 'Other SW Abstractions'
    browns_rock_site: '66450'
    browns_rock_mtype: 'flow'
    browns_rock_waps: ['L35/0906', 'L35/1090']
    hilltop_base_url: http://wateruse.ecan.govt.nz
    hilltop_hts: WaterUse.hts
    hydro_server: edwprod01
Output:
    hydrotel_server: SQL03dev
    detided_point: 7354
    unmod_point: 7355
    other_point: 7356
    quality_code: 2
    log_server: sql04dev
    log_database: Apps_Trace_Log
    log_table: Waimak_Log
